name: cellpy
channels:
    - conda-forge
    - pyviz
dependencies:
    - python >=3.9
    - pip
    - numpy
    - openpyxl
    - xlrd
    - matplotlib
    - cryptography
    - click
    - scipy
    - pandas
    - setuptools
    - ruamel.yaml
    - pyodbc
    - PyGithub
    - cookiecutter
    - tqdm
    - ipython
    - ipywidgets
    - lmfit
    - ipykernel
    - holoviz
    - hdf5
    - pytables
    - python-box
    - jupyter
    - jupyterlab
    - pint
    - plotly
    - sqlalchemy
    - python-dotenv
    - fabric
    - rich
    - dateparser
    - pip:
        - sqlalchemy-access

