name: cellpy_dev
channels:
    - conda-forge
    - defaults
dependencies:
    - python >=3.9
    - pip
    - numpy
    - openpyxl
    - xlrd
    - matplotlib
    - cryptography
    - click
    - scipy
    - pandas >=1.5
    - setuptools
    - ruamel.yaml
    - pyodbc
    - PyGithub
    - cookiecutter
    - tqdm
#    - ipython
#    - ipywidgets
    - lmfit
#    - ipykernel
    - hdf5
    - pytables >=3.6.1
    - python-box
    - pint
    - sqlalchemy >=2.0
    - python-dotenv
    - fabric
    - rich
    - dateparser
    - coverage
    - pytest
    - pytest-timeout
    - pytest-benchmark
    - pip:
        - sqlalchemy-access


